import DataInfo from '../common/DataInfo'
import MeetRecord from '../common/MeetRecord'

export const baseURL = 'https://apis.data.go.kr'
export const apiURL = (no: string) =>
	`https://www.data.go.kr/data/${no}/openapi.do`

export const dailyTrainingInfo: DataInfo = {
	name: '일별훈련 상세정보',
	apiNo: '15058782',
	url: '/B551015/API18_1/dailyTraining_1',
	key: 'hrNo-stTime',
	keyName: {
		chulGubun: '출주예정마',
		hrName: '마명',
		hrNo: '마번',
		meet: '시행경마장명',
		part: '소속조',
		partNo: '조번',
		prGubun: '기승자구분',
		prNo: '기승자사번',
		run1Cnt: '구보',
		run2Cnt: '습보',
		spTime: '조교종료시간',
		stTime: '조교시작시간',
		trDate: '훈련일자',
		trName: '조교사명',
		trTerm: '훈련시간(초)',
	},
}

export const entryHorseWeightInfoInfo: DataInfo = {
	name: '출전마 체중 정보',
	apiNo: '15057498',
	key: 'hrNo-rcDate',
	url: '/B551015/API25_1/entryHorseWeightInfo_1',
	keyName: {
		budam: '시행경마장명',
		chulNo: '마번(출주번호)',
		hrName: '마명',
		hrNo: '마번(고유번호)',
		meet: '제주',
		rcDate: '경주일자',
		rcDays: '경주요일',
		rcDist: '경주거리',
		rcName: '경주명',
		rcNo: '경주번호',
		recentRcDate: '최종출전일',
		wgHr: '마체중',
		wgHrDiff: '증감(kg)',
	},
}

export const jockeyInfoInfo: DataInfo = {
	name: '기수 상세정보',
	apiNo: '15056828',
	url: '/B551015/API12_1/jockeyInfo_1',
	key: 'jkNo',
	keyName: {
		age: '나이',
		birthday: '생년월일',
		debut: '데뷔일자',
		jkName: '기수명',
		jkNo: '기수번호',
		meet: '시행경마장명',
		ord1CntT: '통산1착횟수',
		ord1CntY: '최근1년1착횟수',
		ord2CntT: '통산2착횟수',
		ord2CntY: '최근1년2착횟수',
		ord3CntT: '통산3착횟수',
		ord3CntY: '최근1년3착횟수',
		part: '소속조',
		rcCntT: '통산총출주횟수',
		rcCntY: '최근1년총출주횟수',
		spDate: '은퇴일자',
		wgOther: '기능가능중량_타조',
		wgPart: '기능가능중량_소속조',
	},
}

export const jockeyResultInfo: DataInfo = {
	name: '기수 성적 정보',
	apiNo: '15056591',
	url: '/B551015/API11_1/jockeyResult_1',
	key: 'jkNo',
	keyName: {
		jkName: '기수명',
		jkNo: '기수번호',
		meet: '시행경마장명',
		ord1CntT: '통산1위횟수',
		ord1CntY: '최근1년1위횟수',
		ord2CntT: '통산2위횟수',
		ord2CntY: '최근1년2위횟수',
		qnlRateT: '통산복승률',
		qnlRateY: '최근1년복승률',
		rcCntT: '통산출주횟수',
		rcCntY: '최근1년출주횟수',
		winRateT: '통산승률',
		winRateY: '최근1년승률',
	},
}

export const raceHorseClinicInfo: DataInfo = {
	name: '마필진료 정보',
	apiNo: '15057799',
	url: '/B551015/API16_1/raceHorseClinic_1',
	key: 'clinicDate-hrNo',
	keyName: {
		clinicDate: '진료일자',
		hospiName: '선진경마장제',
		hrName: '마명',
		hrNo: '마번',
		illName1: '진료내역1',
		illName2: '진료내역2',
		meet: '시행경마장명',
		part: '소속조',
	},
}

export const raceHorseInfoInfo: DataInfo = {
	name: '경주마 상세정보',
	apiNo: '15058115',
	key: 'hrNo',
	url: '/B551015/API8_2/raceHorseInfo_2',
	keyName: {
		birthday: '생년월일',
		chaksunT: '통산착순상금',
		faHrName: '부마명',
		faHrNo: '부마번',
		hrLastAmt: '말도입가',
		hrName: '마명',
		hrNo: '마번',
		meet: '시행경마장명',
		moHrName: '모마명',
		moHrNo: '모마번',
		name: '출생지',
		ord1CntT: '통산1착회수',
		ord1CntY: '최근1년1착회수',
		ord2CntT: '통산2착회수',
		ord2CntY: '최근1년2착회수',
		ord3CntT: '통산3착회수',
		ord3CntY: '최근1년3착회수',
		owName: '마주명',
		owNo: '마주번호',
		rank: '등급',
		rating: '레이팅',
		rcCntT: '통산총출주회수',
		rcCntY: '최근1년총출주회수',
		sex: '성별',
		trName: '조교사명',
		trNo: '조교사번호',
	},
}

export const raceHorseResultInfo: DataInfo = {
	name: '경주마 성적 정보',
	apiNo: '15058779',
	url: '/B551015/API15_2/raceHorseResult_2',
	key: 'hrNo',
	keyName: {
		age: '나이',
		chaksunT: '통산착순상금',
		chaksunY: '최근1년착순상금',
		chaksun_6: '최근6개월수득상금',
		debut: '데뷔일자',
		hrName: '마명',
		hrNo: '마번',
		meet: '시행경마장명',
		name: '산지',
		ord1CntT: '통산1착회수',
		ord1CntY: '최근1년1착회수',
		ord2CntT: '통산2착회수',
		ord2CntY: '최근1년2착회수',
		qnlRateT: '통산복승률',
		qnlRateY: '최근1년복승률',
		rcCntT: '통산총출주회수',
		rcCntY: '최근1년총출주회수',
		recentBudam: '최근경주부담종류',
		recentOrd: '최근경주순위',
		recentRank: '최근경주등급',
		recentRating: '최근경주레이팅',
		recentRcDate: '최근경주일자',
		recentRcDist: '최근경주거리',
		recentRcName: '최근경주명',
		recentRcNo: '최근경주번호',
		recentRcTime: '최근경주기록',
		recentWgBudam: '최근경주부담중량',
		recentWgHr: '최근경주마체중',
		sex: '성별',
		winRateT: '통산승률',
		winRateY: '최근1년승률',
	},
}

export const racePlanInfo: DataInfo = {
	name: '경주계획표',
	apiNo: '15056499', // 'https://www.data.go.kr/data/15056499/openapi.do',
	url: '/B551015/API72_1/racePlan_1',
	key: 'meet-rcDate-rcNo',
	keyName: <Record<string, string>>{
		ageCond: '연령조건',
		budam: '부담구분',
		buga1: '1착부가상금',
		buga2: '2착부가상금',
		buga3: '3착부가상금',
		chaksun1: '1착상금',
		chaksun2: '2착상금',
		chaksun3: '3착상금',
		chaksun4: '4착상금',
		chaksun5: '5착상금',
		ilsu: '경주차수',
		meet: '시행경마장명',
		rank: '등급조건',
		rcDate: '경주일자',
		rcDist: '경주거리',
		rcName: '경주명',
		rcNo: '경주번호',
		schStTime: '발주예정시각',
		spRating: '레이팅상한조건',
		stRating: '레이팅하한조건',
	},
}

export const raceResultInfo: DataInfo = {
	name: '경주기록 정보',
	apiNo: '15058305',
	url: '/B551015/API4_2/raceResult_2',
	key: 'meet-rcDate-rcNo-chulNo',
	keyName: <Record<string, string>>{
		age: '연령',
		ageCond: '연령조건',
		buG1fAccTime: '부경G1F통과누적기록',
		buG1fOrd: '부경G1F통과순위',
		buG2fAccTime: '부경G2F통과누적기록',
		buG2fOrd: '부경G2F통과순위',
		buG3fAccTime: '부경G3F통과누적기록',
		buG3fOrd: '부경G3F통과순위',
		buG4fAccTime: '부경G4F통과누적기록',
		buG4fOrd: '부경G4F통과순위',
		buG6fAccTime: '부경G6F통과누적기록',
		buG6fOrd: '부경G6F통과순위',
		buG8fAccTime: '부경G8F통과누적기록',
		buG8fOrd: '부경G8F통과순위',
		buS1fAccTime: '부경S1F통과누적기록',
		buS1fOrd: '부경S1F통과순위',
		buS1fTime: '부경S1F통과기록',
		bu_10_8fTime: '부경10-8F통과기록',
		bu_1fGTime: '부경1F-G통과기록',
		bu_2fGTime: '부경2F-G통과기록',
		bu_3fGTime: '부경3F-G통과기록',
		bu_4_2fTime: '부경4-2F통과기록',
		bu_6_4fTime: '부경6-4F통과기록',
		bu_8_6fTime: '부경8-6F통과기록',
		budam: '부담구분',
		buga1: '부가상금1',
		buga2: '부가상금2',
		buga3: '부가상금3',
		chaksun1: '1착상금',
		chaksun2: '2착상금',
		chaksun3: '3착상금',
		chaksun4: '4착상금',
		chaksun5: '5착상금',
		chulNo: '출주번호',
		diffUnit: '착차',
		hrName: '마명',
		hrNo: '마번',
		ilsu: '경주일수',
		jeG1fTime: '제주G-1F통과기록',
		jeG3fTime: '제주G-3F통과기록',
		jeS1fTime: '제주S-1F통과기록',
		je_1cTime: '제주1코너통과기록',
		je_2cTime: '제주2코너통과기록',
		je_3cTime: '제주3코너통과기록',
		je_4cTime: '제주4코너통과기록',
		jkName: '기수명',
		jkNo: '기수번호',
		meet: '시행경마장명',
		name: '국적',
		ord: '순위',
		owName: '마주명',
		owNo: '마주번호',
		plcOdds: '복승식 배당율',
		prizeCond: '경주조건',
		rank: '등급조건',
		rating: '레이팅(등급)',
		rcDate: '경주일자',
		rcDay: '경주요일',
		rcDist: '경주거리',
		rcName: '경주명',
		rcNo: '경주번호',
		rcTime: '경주기록',
		seG1fAccTime: '서울G1F통과누적기록',
		seG3fAccTime: '서울G3F통과누적기록',
		seS1fAccTime: '서울S1F통과누적기록',
		se_1cAccTime: '서울1코너통과누적기록',
		se_2cAccTime: '서울2코너통과누적기록',
		se_3cAccTime: '서울3코너통과누적기록',
		se_4cAccTime: '서울4코너통과누적기록',
		sex: '성별',
		sjG1fOrd: '서울,제주G1F구간통과순위(서울,제주공통)',
		sjG3fOrd: '서울,제주G3F구간통과순위(서울,제주공통)',
		sjS1fOrd: '서울,제주S1F구간통과순위(서울,제주공통)',
		sj_1cOrd: '서울,제주1코너구간통과순위(서울,제주공통)',
		sj_2cOrd: '서울,제주2코너구간통과순위(서울,제주공통)',
		sj_3cOrd: '서울,제주3코너구간통과순위(서울,제주공통)',
		sj_4cOrd: '서울,제주4코너구간통과순위(서울,제주공통)',
		trName: '조교사명',
		trNo: '조교사번호',
		track: '주로',
		weather: '날씨',
		wgBudam: '부담중량',
		wgHr: '마체중',
		winOdds: '단승식 배당율',
	},
}

export const ridingTestResultInfo: DataInfo = {
	name: '주행심사 상세결과',
	apiNo: '15056974',
	url: '/B551015/API20_1/ridingTestResult_1',
	key: 'meet-trainDate-trainNo-chulNo',
	keyName: {
		age: '연령',
		chulNo: '마번(출주번호)',
		daySerial: '심사차수',
		diffUnit: '도착차',
		g1f: 'G1F 순위',
		g2f: 'G2F(부경) 순위',
		g3f_4c: 'G3F/4C(부경/서울,제주) 순위',
		g4f_3c: 'G4F/3C(부경/서울,제주) 순위',
		g6f_2c: 'G6F/2C(부경/서울,제주) 순위',
		g8f_1c: 'G8F/1C(부경/서울,제주) 순위',
		hrName: '마명',
		hrNo: '마번(고유번호)',
		jkName: '기수명',
		jkNo: '기수번호',
		majong: '마종(제주한정)',
		meet: '시행경마장명',
		name: '산지',
		nopassReason: '불합격사유',
		ord: '순위',
		passFlag: '판정',
		passtime_3f: '3펄롱',
		passtime_4f: '4펄롱',
		rcTime: '통과기록',
		rcTimeG1f: 'G1F 기록',
		rcTimeG3f: 'G3F 기록',
		rcTimeG400: 'G400기록(부경)',
		rcTimeS1f: 'S1F 기록',
		rcTime_1c: '1C 기록',
		rcTime_2c: '2C 기록',
		rcTime_3c: '3C 기록',
		rcTime_400: '400 기록(부경)',
		rcTime_4c: '4C 기록',
		reason: '검사사유',
		s1f: 'S1F 순위',
		sex: '성별',
		trName: '조교사명',
		trNo: '조교사번호',
		track: '주로상태',
		trainDate: '주행심사일자',
		trainDays: '주행심사요일',
		trainNo: '경주번호',
		weather: '날씨',
		wgBudam: '부담중량',
		wgHr: '마체중',
		wgJkAdd: '기수초과중량',
	},
}

export const sectionRecordInfo: DataInfo = {
	name: '마필 구간별 경주기록',
	apiNo: '15057859',
	url: '/B551015/API37_1/sectionRecord_1',
	key: 'meet-rcDate-rcNo-chulNo-hrNo',
	keyName: {
		ARcTimeG1f: 'G1F 평균기록',
		ARcTimeG3f: 'G3F 평균기록',
		ARcTimeS1f: 'S1F 평균기록',
		ARcTime_3c: '3C 평균기록',
		ARcTime_4c: '4C 평균기록',
		chulNo: '출주번호',
		FRcTimeG1f: 'G1F 최고기록',
		FRcTimeG3f: 'G3F 최고기록',
		FRcTimeS1f: 'S1F 최고기록',
		FRcTime_3c: '3C 최고기록',
		FRcTime_4c: '4C 최고기록',
		hrName: '마명',
		hrNo: '마번',
		meet: '시행경마장명',
		rcDate: '경주일',
		rcDist: '경주거리',
		rcNo: '경주번호',
		rcTime: '최고기록',
		SRcTimeG1f: 'G1F 최저기록',
		SRcTimeG3f: 'G3F 최저기록',
		SRcTimeS1f: 'S1F 최저기록',
		SRcTime_3c: '3C 최저기록',
		SRcTime_4c: '4C 최저기록',
	},
}

export const startingTrainingInfo: DataInfo = {
	name: '출발훈련 정보',
	apiNo: '15059043',
	url: '/B551015/API22_1/startingTranning_1',
	key: 'hrNo-trDate',
	keyName: {
		hrName: '마명',
		hrNo: '마번',
		meet: '시행경마장명',
		part: '소속조',
		partNo: '조번',
		prName: '기승자',
		remark: '훈련결과',
		trDate: '훈련일자',
	},
}

export const swimTrainingInfo: DataInfo = {
	name: '수영훈련정보',
	apiNo: '15063981',
	url: '/B551015/API216/SwimTr',
	key: 'hrNo-trDate',
	keyName: {
		cnt: '수영조교횟수',
		horsepart: '마필조번',
		horsepartMemo: '마필조번메모',
		hrName: '마명',
		hrNo: '마명',
		meet: '경마장명',
		trDate: '수영조교일',
		trName: '조교사명',
		trpart: '조교사조번',
	},
}

export const trackInfo: DataInfo = {
	name: '경주로정보',
	apiNo: '15063953',
	url: '/B551015/API189_1/Track_1',
	key: 'meet-rcDate-rcNo',
	keyName: {
		humidityRel: '상대습도',
		meet: '경마장명',
		rcDate: '경주일자',
		rcNo: '경주번호',
		salinity: '염도',
		temperature: '기온',
		track: '주로상태',
		waterPercent: '함수율',
		weather: '날씨',
		windDirection: '풍향',
		windSpeed: '풍속(M/s)',
	},
}

export const trainerInfoInfo: DataInfo = {
	name: '조교사 상세정보',
	apiNo: '15057915',
	url: '/B551015/API19_1/trainerInfo_1',
	key: 'trNo',
	keyName: {
		age: '나이',
		birthday: '생년월일',
		meet: '시행경마장명',
		ord1CntT: '통산1위횟수',
		ord1CntY: '최근1년1위횟수',
		ord2CntT: '통산2위횟수',
		ord2CntY: '최근1년2위횟수',
		ord3CntT: '통산3위횟수',
		ord3CntY: '최근1년3위횟수',
		part: '소속조',
		plcRateT: '통산연승률',
		plcRateY: '최근1년연승률',
		qnlRateT: '통산복승률',
		qnlRateY: '최근1년복승률',
		rcCntT: '통산출주횟수',
		rcCntY: '최근1년출주횟수',
		stDate: '데뷔일자',
		trName: '조교사명',
		trNo: '조교사번호',
		winRateT: '통산승률',
		winRateY: '최근1년승률',
	},
}

export const Meet: Record<string, MeetRecord> = {
	전체: {
		no: 0,
		label: '전체',
		color: 'grey-7',
		colorCode: '#616161',
		imagePub: '',
		name: '',
		dists: [],
	},
	서울: {
		no: 1,
		label: '서울',
		color: 'primary',
		colorCode: '#0077DD',
		imagePub: 'ijrc_pub',
		name: '서울',
		dists: [1000, 1200, 1300, 1400, 1600, 1700, 1800, 1900, 2000, 2300],
	},
	제주: {
		no: 2,
		label: '제주',
		color: 'negative',
		colorCode: '#DB0000',
		imagePub: 'jris_pub',
		name: '제주',
		dists: [400, 800, 900, 1000, 1100, 1200, 1400, 1610, 1700, 1800],
	},
	부산경남: {
		no: 3,
		label: '부경',
		color: 'positive',
		colorCode: '#1CB500',
		imagePub: 'pris_pub',
		name: '부산경남',
		dists: [1000, 1200, 1300, 1400, 1500, 1600, 1800, 1900, 2000, 2200],
	},
	부경: {
		// api meet '부산경남' or '부경'
		no: 3,
		label: '부경',
		color: 'positive',
		colorCode: '#1CB500',
		imagePub: 'pris_pub',
		name: '부산경남',
		dists: [1000, 1200, 1300, 1400, 1500, 1600, 1800, 1900, 2000, 2200],
	},
}
export const MeetInfos = [Meet.전체, Meet.서울, Meet.제주, Meet.부산경남]

export const WeekMeets: Record<number, string[]> = {
	5: ['제주', '부산경남'],
	6: ['서울', '제주'],
	0: ['서울', '부산경남'],
}

export const SexText: Record<string, string> = {
	수: '수말',
	암: '암말',
	거: '거세말',
}
